version: '3.7'

networks:
  homelan:
    name: homelan
    external: true

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab-${GITLAB_SERVER_NR}.fritz.box'
    container_name: gitlab-${GITLAB_SERVER_NR}
    environment:
      GITLAB_SERVER_NR: ${GITLAB_SERVER_NR}
      GITLAB_IP: ${GITLAB_IP}
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab-${GITLAB_SERVER_NR}.fritz.box:80'
    volumes:
      - /ssd/Pods/gitlab-${GITLAB_SERVER_NR}/web/etc/gitlab:/etc/gitlab
      - /ssd/Pods/gitlab-${GITLAB_SERVER_NR}/web/var/opt/gitlab:/var/opt/gitlab
      - /ssd/Pods/gitlab-${GITLAB_SERVER_NR}/web/var/log/gitlab:/var/log/gitlab
    networks:
      homelan:
        ipv4_address: 192.168.178.${GITLAB_IP}1

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner-${GITLAB_SERVER_NR}
    environment:
      GITLAB_SERVER_NR: ${GITLAB_SERVER_NR}
      GITLAB_IP: ${GITLAB_IP}
    restart: always
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /ssd/Pods/gitlab-${GITLAB_SERVER_NR}/gitlab-runner/etc/gitlab-runner:/etc/gitlab-runner
    networks:
      homelan:
        ipv4_address: 192.168.178.${GITLAB_IP}2


