version: '3.7'

networks:
  homelan:
    external: true

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab-2.fritz.box'
    container_name: gitlab-2
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab-2.fritz.box:80'
    volumes:
      - /ssd/Pods/gitlab-2/web/etc/gitlab:/etc/gitlab
      - /ssd/Pods/gitlab-2/web/var/opt/gitlab:/var/opt/gitlab
      - /ssd/Pods/gitlab-2/web/var/log/gitlab:/var/log/gitlab
    networks:
      homelan:
        ipv4_address: 192.168.178.21
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner-2   
    restart: always
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /ssd/Pods/gitlab-2/gitlab-runner/etc/gitlab-runner:/etc/gitlab-runner
    networks:
      homelan:
        ipv4_address: 192.168.178.22

